// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1:string):Promise<void>;

export function DeleteFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function MoveFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
