// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1) {
  return window['go']['services']['FileServices']['CreateFile'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['services']['FileServices']['ReadFile'](arg1);
}
