// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1) {
  return window['go']['services']['FileServices']['CreateFile'](arg1);
}

export function DeleteFile(arg1, arg2, arg3) {
  return window['go']['services']['FileServices']['DeleteFile'](arg1, arg2, arg3);
}

export function MoveFile(arg1, arg2, arg3) {
  return window['go']['services']['FileServices']['MoveFile'](arg1, arg2, arg3);
}

export function ReadFile(arg1) {
  return window['go']['services']['FileServices']['ReadFile'](arg1);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['services']['FileServices']['RenameFile'](arg1, arg2, arg3);
}

export function WriteFile(arg1, arg2) {
  return window['go']['services']['FileServices']['WriteFile'](arg1, arg2);
}
