// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CreateFile(arg1:string):Promise<services.Payload>;

export function CreateFolder(arg1:string):Promise<services.Payload>;

export function DeleteFile(arg1:string,arg2:string,arg3:string):Promise<services.Payload>;

export function MoveFile(arg1:string,arg2:string,arg3:string):Promise<services.Payload>;

export function ReadFile(arg1:string):Promise<services.Payload>;

export function RenameFile(arg1:string,arg2:string,arg3:string):Promise<services.Payload>;

export function WriteFile(arg1:string,arg2:string):Promise<services.Payload>;
