// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function LoadLib(arg1:string):Promise<Array<services.LibraryTree>>;

export function MakeLib(arg1:string,arg2:string):Promise<void>;
