// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function LibTree(arg1:string):Promise<Array<services.LibraryTree>>;

export function LoadLibConfig(arg1:string):Promise<string|boolean>;

export function MakeLib(arg1:string,arg2:string):Promise<void>;

export function UpdateLibConfig(arg1:string,arg2:string):Promise<void>;
