// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function BuildProjectTree(arg1:string):Promise<Array<services.ProjectNode>>;

export function DeleteProject(arg1:string,arg2:string,arg3:string):Promise<services.Payload>;

export function MakeProject(arg1:string,arg2:string):Promise<services.Payload>;

export function ProjectTree(arg1:string):Promise<services.Payload>;

export function RenameProject(arg1:string,arg2:string,arg3:string):Promise<services.Payload>;
