// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MakeProject(arg1, arg2) {
  return window['go']['services']['ProjectServices']['MakeProject'](arg1, arg2);
}

export function ProjectTree(arg1) {
  return window['go']['services']['ProjectServices']['ProjectTree'](arg1);
}
