// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildProjectTree(arg1) {
  return window['go']['services']['ProjectServices']['BuildProjectTree'](arg1);
}

export function DeleteProject(arg1, arg2, arg3) {
  return window['go']['services']['ProjectServices']['DeleteProject'](arg1, arg2, arg3);
}

export function MakeProject(arg1, arg2) {
  return window['go']['services']['ProjectServices']['MakeProject'](arg1, arg2);
}

export function ProjectTree(arg1) {
  return window['go']['services']['ProjectServices']['ProjectTree'](arg1);
}

export function RenameProject(arg1, arg2, arg3) {
  return window['go']['services']['ProjectServices']['RenameProject'](arg1, arg2, arg3);
}
