// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function MakeProject(arg1:string,arg2:string):Promise<services.Payload>;

export function ProjectTree(arg1:string):Promise<Array<services.ProjectNode>>;
