// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigCheck() {
  return window['go']['services']['StartUpServices']['ConfigCheck']();
}

export function StartUpManager(arg1, arg2) {
  return window['go']['services']['StartUpServices']['StartUpManager'](arg1, arg2);
}
