// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function ConfigCheck():Promise<services.Payload>;

export function StartUpManager(arg1:string,arg2:string):Promise<string>;

export function UpdateConfig(arg1:string,arg2:string):Promise<void>;
