// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigCheck():Promise<string|boolean>;

export function StartUpManager(arg1:string,arg2:string):Promise<string>;

export function UpdateConfig(arg1:string,arg2:string):Promise<void>;
